// GENERATED by tools/gen-akai-map.py — do not edit by hand.
// APC40 mkII mapping snapshot for the read-only AKAI page.
export const APC = {
 "meta": {
  "composition": "26autoV_CAMPUSJ_0721",
  "mapping": "AkaiXboxMaion.xml",
  "generated": "2026-07-26",
  "shortcuts": 166
 },
 "grid": [
  {
   "zone": "FX 1 · flash clips",
   "cells": [
    {
     "label": "GENERAXYZ_07",
     "more": 1,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 2 (GeneraXYZ_07)",
       "path": "/composition/layers/12/clips/2/connect"
      },
      {
       "name": "FX 1 clip 2 (GeneraXYZ_07) video/opacity",
       "path": "/composition/layers/12/clips/2/video/opacity"
      }
     ],
     "hex": null,
     "note": 32
    },
    {
     "label": "FLASH MASTER",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 3 (FLASH MASTER)",
       "path": "/composition/layers/12/clips/3/connect"
      }
     ],
     "hex": null,
     "note": 33
    },
    {
     "label": "FLASH MASTER",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 4 (FLASH MASTER)",
       "path": "/composition/layers/12/clips/4/connect"
      }
     ],
     "hex": null,
     "note": 34
    },
    {
     "label": "INVERT",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 5 (INVERT)",
       "path": "/composition/layers/12/clips/5/connect"
      }
     ],
     "hex": null,
     "note": 35
    },
    {
     "label": "PIXELATE",
     "more": 1,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 6 (PIXELATE)",
       "path": "/composition/layers/12/clips/6/connect"
      },
      {
       "name": "object connect",
       "path": "/composition/objects/1730384339532/connect"
      }
     ],
     "hex": null,
     "note": 36
    },
    {
     "label": "FE STR",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 7 (FE STR)",
       "path": "/composition/layers/12/clips/7/connect"
      }
     ],
     "hex": null,
     "note": 37
    },
    {
     "label": "SUCK IT!",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 8 (SUCK IT!)",
       "path": "/composition/layers/12/clips/8/connect"
      }
     ],
     "hex": null,
     "note": 38
    },
    {
     "label": "SLICE STROBE",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch FX 1 clip 9 (SLICE STROBE)",
       "path": "/composition/layers/12/clips/9/connect"
      }
     ],
     "hex": null,
     "note": 39
    }
   ]
  },
  {
   "zone": "BG + BOOMER color",
   "cells": [
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      },
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      }
     ],
     "hex": "#ff0000",
     "note": 24
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      },
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      }
     ],
     "hex": "#ff8000",
     "note": 25
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      },
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      }
     ],
     "hex": "#ffff00",
     "note": 26
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      },
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      }
     ],
     "hex": "#00ff00",
     "note": 27
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      },
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      }
     ],
     "hex": "#00ffff",
     "note": 28
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      },
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      }
     ],
     "hex": "#0000ff",
     "note": 29
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      },
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      }
     ],
     "hex": "#8000ff",
     "note": 30
    },
    {
     "label": "",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer colorizecolor/palette/colors (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizecolor/palette/colors"
      },
      {
       "name": "STOCKS group video/effects/colorize/effect/color/palette/colors",
       "path": "/composition/groups/1/video/effects/colorize/effect/color/palette/colors"
      }
     ],
     "hex": "#ff00ff",
     "note": 31
    }
   ]
  },
  {
   "zone": "LOGO MAIN color",
   "cells": [
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff0000",
     "note": 16
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff8000",
     "note": 17
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ffff00",
     "note": 18
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#00ff00",
     "note": 19
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#00ffff",
     "note": 20
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#0000ff",
     "note": 21
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#8000ff",
     "note": 22
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff00ff",
     "note": 23
    }
   ]
  },
  {
   "zone": "LOGO DJ color",
   "cells": [
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff0000",
     "note": 8
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff8000",
     "note": 9
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ffff00",
     "note": 10
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#00ff00",
     "note": 11
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#00ffff",
     "note": 12
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#0000ff",
     "note": 13
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#8000ff",
     "note": 14
    },
    {
     "label": "",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ video/effects/outlinehaze/effect/color/palette/colors",
       "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/color/palette/colors"
      }
     ],
     "hex": "#ff00ff",
     "note": 15
    }
   ]
  },
  {
   "zone": "VIDEO 1 clips",
   "cells": [
    {
     "label": "V1 C2",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 2",
       "path": "/composition/layers/1/clips/2/connect"
      }
     ],
     "hex": null,
     "note": 0
    },
    {
     "label": "V1 C3",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 3",
       "path": "/composition/layers/1/clips/3/connect"
      }
     ],
     "hex": null,
     "note": 1
    },
    {
     "label": "V1 C4",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 4",
       "path": "/composition/layers/1/clips/4/connect"
      }
     ],
     "hex": null,
     "note": 2
    },
    {
     "label": "V1 C5",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 5",
       "path": "/composition/layers/1/clips/5/connect"
      }
     ],
     "hex": null,
     "note": 3
    },
    {
     "label": "V1 C6",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 6",
       "path": "/composition/layers/1/clips/6/connect"
      }
     ],
     "hex": null,
     "note": 4
    },
    {
     "label": "V1 C7",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 7",
       "path": "/composition/layers/1/clips/7/connect"
      }
     ],
     "hex": null,
     "note": 5
    },
    {
     "label": "V1 C8",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 8",
       "path": "/composition/layers/1/clips/8/connect"
      }
     ],
     "hex": null,
     "note": 6
    },
    {
     "label": "V1 C9",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "launch VIDEO 1 clip 9",
       "path": "/composition/layers/1/clips/9/connect"
      }
     ],
     "hex": null,
     "note": 7
    }
   ]
  }
 ],
 "scenes": [
  {
   "label": "STOCK GREYSKEE",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "STOCKS group video/effects/colorize/effect/greyskeep",
     "path": "/composition/groups/1/video/effects/colorize/effect/greyskeep"
    }
   ],
   "hex": null,
   "note": 82
  },
  {
   "label": "STOCK COLORIZE ⊘",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "STOCKS group video/effects/colorize/bypassed",
     "path": "/composition/groups/1/video/effects/colorize/bypassed"
    }
   ],
   "hex": null,
   "note": 83
  },
  {
   "label": "SLICE ST SLICE-",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "SLICE STROBE video/effects/slicestrobe/effect/slice-o-rama",
     "path": "/composition/objects/1720199917741/video/effects/slicestrobe/effect/slice-o-rama"
    }
   ],
   "hex": null,
   "note": 84
  },
  {
   "label": "DISTORTION ⊘",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "distortion on/off (composition FX)",
     "path": "/composition/video/effects/distortion/bypassed"
    }
   ],
   "hex": null,
   "note": 85
  },
  {
   "label": "COLORMORPH ⊘",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "colormorph on/off (composition FX)",
     "path": "/composition/video/effects/colormorph/bypassed"
    }
   ],
   "hex": null,
   "note": 86
  }
 ],
 "strip": [
  {
   "name": "CLIP STOP",
   "note": 52,
   "cells": [
    {
     "label": "BOOM BLUR BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer blurbpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/blurbpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 1
    },
    {
     "label": "BOOM EXPOS BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer exposurebpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/exposurebpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 2
    },
    {
     "label": "BOOM EDGE BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer edgebpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/edgebpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 3
    },
    {
     "label": "BOOM BLOW BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer blowbpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/blowbpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 4
    },
    {
     "label": "BOOM INVER BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer invertbpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/invertbpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 5
    },
    {
     "label": "BOOM COLOR BPM",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "boomer colorizebpm (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorizebpm"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 6
    },
    {
     "label": "PUSH2 CHOIC",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "pusher2 choicein (composition FX)",
       "path": "/composition/video/effects/pusher2/effect/choicein"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 7
    },
    {
     "label": "PUSH1 CHOIC",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "pusher choicein (composition FX)",
       "path": "/composition/video/effects/pusher/effect/choicein"
      }
     ],
     "hex": null,
     "note": 52,
     "ch": 8
    }
   ]
  },
  {
   "name": "TRK SELECT",
   "note": 51,
   "cells": [
    {
     "label": "BOOM BLUR",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer blur (composition FX)",
       "path": "/composition/video/effects/boomer/effect/blur"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 1
    },
    {
     "label": "BOOM EXPOSU",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer exposure (composition FX)",
       "path": "/composition/video/effects/boomer/effect/exposure"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 2
    },
    {
     "label": "BOOM EDGE",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer edge (composition FX)",
       "path": "/composition/video/effects/boomer/effect/edge"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 3
    },
    {
     "label": "BOOM BLOW",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer blow (composition FX)",
       "path": "/composition/video/effects/boomer/effect/blow"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 4
    },
    {
     "label": "BOOM INVERT",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer invert (composition FX)",
       "path": "/composition/video/effects/boomer/effect/invert"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 5
    },
    {
     "label": "BOOM COLORI",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "boomer colorize (composition FX)",
       "path": "/composition/video/effects/boomer/effect/colorize"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 6
    },
    {
     "label": "PUSH 1",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "pusher push! (composition FX)",
       "path": "/composition/video/effects/pusher/effect/push!"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 7
    },
    {
     "label": "PUSH 2",
     "more": 0,
     "tag": "hold",
     "detail": [
      {
       "name": "pusher2 push! (composition FX)",
       "path": "/composition/video/effects/pusher2/effect/push!"
      }
     ],
     "hex": null,
     "note": 51,
     "ch": 8
    }
   ]
  },
  {
   "name": "ACTIVATOR",
   "note": 50,
   "cells": [
    {
     "label": "VIDEO 1 SEL",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 1 select",
       "path": "/composition/layers/1/select"
      }
     ],
     "hex": null,
     "note": 50,
     "ch": 1
    },
    {
     "label": "VIDEO 2 SEL",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 2 select",
       "path": "/composition/layers/2/select"
      }
     ],
     "hex": null,
     "note": 50,
     "ch": 2
    },
    {
     "label": "VIDEO 3 SEL",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 3 select",
       "path": "/composition/layers/3/select"
      }
     ],
     "hex": null,
     "note": 50,
     "ch": 3
    },
    {
     "label": "VIDEO 4 SEL",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 4 select",
       "path": "/composition/layers/4/select"
      }
     ],
     "hex": null,
     "note": 50,
     "ch": 4
    },
    {
     "label": "LOGOS SEL",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGOS group select",
       "path": "/composition/groups/3/select"
      }
     ],
     "hex": null,
     "note": 50,
     "ch": 5
    },
    null,
    null,
    null
   ]
  },
  {
   "name": "SOLO/CUE",
   "note": 49,
   "cells": [
    {
     "label": "VIDEO 1 SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 1 solo",
       "path": "/composition/layers/1/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 1
    },
    {
     "label": "VIDEO 2 SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 2 solo",
       "path": "/composition/layers/2/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 2
    },
    {
     "label": "VIDEO 3 SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 3 solo",
       "path": "/composition/layers/3/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 3
    },
    {
     "label": "VIDEO 4 SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 4 solo",
       "path": "/composition/layers/4/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 4
    },
    {
     "label": "LOGO DJ SOLO",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ solo",
       "path": "/composition/layers/8/solo"
      },
      {
       "name": "LOGO OPT1 solo",
       "path": "/composition/layers/10/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 5
    },
    {
     "label": "LOGO MAIN SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN solo",
       "path": "/composition/layers/9/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 6
    },
    null,
    {
     "label": "STOCKS SOLO",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group solo",
       "path": "/composition/groups/1/solo"
      }
     ],
     "hex": null,
     "note": 49,
     "ch": 8
    }
   ]
  },
  {
   "name": "REC ARM",
   "note": 48,
   "cells": [
    null,
    {
     "label": "VIDEO 2 ⊘",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 2 bypassed",
       "path": "/composition/layers/2/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 2
    },
    {
     "label": "VIDEO 3 ⊘",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 3 bypassed",
       "path": "/composition/layers/3/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 3
    },
    {
     "label": "VIDEO 4 ⊘",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "VIDEO 4 bypassed",
       "path": "/composition/layers/4/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 4
    },
    {
     "label": "LOGO DJ ⊘",
     "more": 1,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO DJ bypassed",
       "path": "/composition/layers/8/bypassed"
      },
      {
       "name": "LOGO OPT1 bypassed",
       "path": "/composition/layers/10/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 5
    },
    {
     "label": "LOGO MAIN ⊘",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "LOGO MAIN bypassed",
       "path": "/composition/layers/9/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 6
    },
    null,
    {
     "label": "STOCKS ⊘",
     "more": 0,
     "tag": "toggle",
     "detail": [
      {
       "name": "STOCKS group bypassed",
       "path": "/composition/groups/1/bypassed"
      }
     ],
     "hex": null,
     "note": 48,
     "ch": 8
    }
   ]
  }
 ],
 "knobs": {
  "device": [
   {
    "label": "STOCK D1",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link1",
      "path": "/composition/objects/1704033799835/dashboard/link1"
     }
    ],
    "hex": null,
    "cc": 16
   },
   {
    "label": "STOCK D2",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link2",
      "path": "/composition/objects/1704033799835/dashboard/link2"
     }
    ],
    "hex": null,
    "cc": 17
   },
   {
    "label": "STOCK D3",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link3",
      "path": "/composition/objects/1704033799835/dashboard/link3"
     }
    ],
    "hex": null,
    "cc": 18
   },
   {
    "label": "STOCK D4",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link4",
      "path": "/composition/objects/1704033799835/dashboard/link4"
     }
    ],
    "hex": null,
    "cc": 19
   },
   {
    "label": "STOCK D5",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link5",
      "path": "/composition/objects/1704033799835/dashboard/link5"
     }
    ],
    "hex": null,
    "cc": 20
   },
   {
    "label": "STOCK D6",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link6",
      "path": "/composition/objects/1704033799835/dashboard/link6"
     }
    ],
    "hex": null,
    "cc": 21
   },
   {
    "label": "STOCK D7",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link7",
      "path": "/composition/objects/1704033799835/dashboard/link7"
     }
    ],
    "hex": null,
    "cc": 22
   },
   {
    "label": "STOCK D8",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS dashboard/link8",
      "path": "/composition/objects/1704033799835/dashboard/link8"
     }
    ],
    "hex": null,
    "cc": 23
   }
  ],
  "track": [
   {
    "label": "FFT GAIN",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "/audiodevicemanager/params/fftinputgain",
      "path": "/audiodevicemanager/params/fftinputgain"
     }
    ],
    "hex": null,
    "cc": 48
   },
   {
    "label": "PUSH1 FADEO",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "pusher fadeouttime (composition FX)",
      "path": "/composition/video/effects/pusher/effect/fadeouttime"
     }
    ],
    "hex": null,
    "cc": 49
   },
   {
    "label": "PUSH2 FADEO",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "pusher2 fadeouttime (composition FX)",
      "path": "/composition/video/effects/pusher2/effect/fadeouttime"
     }
    ],
    "hex": null,
    "cc": 50
   },
   {
    "label": "FLASH MA STROBE",
    "more": 4,
    "tag": "abs",
    "detail": [
     {
      "name": "FLASH MASTER video/effects/flashmaster/effect/strobespeed",
      "path": "/composition/objects/1779485363427/video/effects/flashmaster/effect/strobespeed"
     },
     {
      "name": "PIXELATE video/effects/flashmaster/effect/strobespeed",
      "path": "/composition/objects/1779483107822/video/effects/flashmaster/effect/strobespeed"
     },
     {
      "name": "INVERT video/effects/flashmaster/effect/strobespeed",
      "path": "/composition/objects/1751651107760/video/effects/flashmaster/effect/strobespeed"
     },
     {
      "name": "FE STR video/effects/flashmaster/effect/strobespeed",
      "path": "/composition/objects/1779482643740/video/effects/flashmaster/effect/strobespeed"
     },
     {
      "name": "SLICE STROBE video/effects/slicestrobe/effect/speed",
      "path": "/composition/objects/1720199917741/video/effects/slicestrobe/effect/speed"
     }
    ],
    "hex": null,
    "cc": 51
   },
   null,
   {
    "label": "LOGO MAI GLOW",
    "more": 1,
    "tag": "abs",
    "detail": [
     {
      "name": "LOGO MAIN video/effects/outlinehaze/effect/glow",
      "path": "/composition/objects/1720292788195/video/effects/outlinehaze/effect/glow"
     },
     {
      "name": "LOGO DJ video/effects/outlinehaze/effect/glow",
      "path": "/composition/objects/1704033798514/video/effects/outlinehaze/effect/glow"
     }
    ],
    "hex": null,
    "cc": 53
   },
   {
    "label": "UI SCROLL ↔",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "/application/ui/clipsscrollhorizontal",
      "path": "/application/ui/clipsscrollhorizontal"
     }
    ],
    "hex": null,
    "cc": 54
   },
   {
    "label": "UI SCROLL ↕",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "/application/ui/clipsscrollvertical",
      "path": "/application/ui/clipsscrollvertical"
     }
    ],
    "hex": null,
    "cc": 55
   }
  ]
 },
 "faders": {
  "tracks": [
   {
    "label": "VIDEO 1",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "VIDEO 1 master",
      "path": "/composition/layers/1/master"
     }
    ],
    "hex": null,
    "ch": 1
   },
   {
    "label": "VIDEO 2",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "VIDEO 2 master",
      "path": "/composition/layers/2/master"
     }
    ],
    "hex": null,
    "ch": 2
   },
   {
    "label": "VIDEO 3",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "VIDEO 3 master",
      "path": "/composition/layers/3/master"
     }
    ],
    "hex": null,
    "ch": 3
   },
   {
    "label": "VIDEO 4",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "VIDEO 4 master",
      "path": "/composition/layers/4/master"
     }
    ],
    "hex": null,
    "ch": 4
   },
   {
    "label": "LOGO DJ",
    "more": 1,
    "tag": "abs",
    "detail": [
     {
      "name": "LOGO DJ master",
      "path": "/composition/layers/8/master"
     },
     {
      "name": "LOGO OPT1 master",
      "path": "/composition/layers/10/master"
     }
    ],
    "hex": null,
    "ch": 5
   },
   {
    "label": "LOGO MAIN",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "LOGO MAIN master",
      "path": "/composition/layers/9/master"
     }
    ],
    "hex": null,
    "ch": 6
   },
   {
    "label": "INPUT",
    "more": 4,
    "tag": "abs",
    "detail": [
     {
      "name": "INPUT master",
      "path": "/composition/layers/11/master"
     },
     {
      "name": "BANNER group master",
      "path": "/composition/groups/2/master"
     },
     {
      "name": "BANNER OPT 2 master",
      "path": "/composition/layers/5/master"
     },
     {
      "name": "BANNER OPT 1 master",
      "path": "/composition/layers/6/master"
     },
     {
      "name": "BANNER MAIN master",
      "path": "/composition/layers/7/master"
     }
    ],
    "hex": null,
    "ch": 7
   },
   {
    "label": "STOCKS GRP",
    "more": 0,
    "tag": "abs",
    "detail": [
     {
      "name": "STOCKS group master",
      "path": "/composition/groups/1/master"
     }
    ],
    "hex": null,
    "ch": 8
   }
  ],
  "master": {
   "label": "COMP MASTER",
   "more": 0,
   "tag": "abs",
   "detail": [
    {
     "name": "master",
     "path": "/composition/master"
    }
   ],
   "hex": null
  },
  "crossfader": {
   "label": "CROSSFADER",
   "more": 0,
   "tag": "abs",
   "detail": [
    {
     "name": "crossfader/phase",
     "path": "/composition/crossfader/phase"
    }
   ],
   "hex": null
  }
 },
 "buttons": [
  {
   "label": "LOGO OPT1 ⊘",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "LOGO OPT1 bypassed",
     "path": "/composition/layers/10/bypassed"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 60,
   "ch": 1,
   "name": "BANK ←"
  },
  {
   "label": "TAP",
   "more": 0,
   "tag": "hold",
   "detail": [
    {
     "name": "tempo tap",
     "path": "/composition/tempocontroller/tempotap"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 80,
   "ch": 1,
   "name": "MASTER"
  },
  {
   "label": "COMP ⊘",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "bypassed",
     "path": "/composition/bypassed"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 81,
   "ch": 1,
   "name": "STOP ALL CLIPS"
  },
  {
   "label": "METRONOME",
   "more": 0,
   "tag": "toggle",
   "detail": [
    {
     "name": "tempo metronome",
     "path": "/composition/tempocontroller/metronome"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 87,
   "ch": 1,
   "name": "PAN"
  },
  {
   "label": "TEMPO ±",
   "more": 0,
   "tag": "step",
   "detail": [
    {
     "name": "tempo up/down",
     "path": "/composition/tempocontroller/tempo"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 88,
   "ch": 1,
   "name": "SENDS"
  },
  {
   "label": "TEMPO ±",
   "more": 0,
   "tag": "step",
   "detail": [
    {
     "name": "tempo up/down",
     "path": "/composition/tempocontroller/tempo"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 89,
   "ch": 1,
   "name": "USER"
  },
  {
   "label": "RESYNC",
   "more": 0,
   "tag": "hold",
   "detail": [
    {
     "name": "tempo resync",
     "path": "/composition/tempocontroller/resync"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 90,
   "ch": 1,
   "name": "METRONOME"
  },
  {
   "label": "TAP",
   "more": 0,
   "tag": "hold",
   "detail": [
    {
     "name": "tempo tap",
     "path": "/composition/tempocontroller/tempotap"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 99,
   "ch": 1,
   "name": "TAP TEMPO"
  },
  {
   "label": "TEMPO ±",
   "more": 0,
   "tag": "step",
   "detail": [
    {
     "name": "tempo up/down",
     "path": "/composition/tempocontroller/tempo"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 100,
   "ch": 1,
   "name": "NUDGE −"
  },
  {
   "label": "TEMPO ±",
   "more": 0,
   "tag": "step",
   "detail": [
    {
     "name": "tempo up/down",
     "path": "/composition/tempocontroller/tempo"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 101,
   "ch": 1,
   "name": "NUDGE +"
  },
  {
   "label": "PLAY",
   "more": 1,
   "tag": "",
   "detail": [
    {
     "name": "tempo play",
     "path": "/composition/tempocontroller/play"
    },
    {
     "name": "tempo play",
     "path": "/composition/tempocontroller/play"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 102,
   "ch": 1,
   "name": "SESSION REC"
  },
  {
   "label": "STOCK ACUARELA ⊘",
   "more": 7,
   "tag": "toggle",
   "detail": [
    {
     "name": "STOCKS group video/effects/acuarela/bypassed",
     "path": "/composition/groups/1/video/effects/acuarela/bypassed"
    },
    {
     "name": "STOCKS group video/effects/metashape/bypassed",
     "path": "/composition/groups/1/video/effects/metashape/bypassed"
    },
    {
     "name": "STOCKS group video/effects/goo/bypassed",
     "path": "/composition/groups/1/video/effects/goo/bypassed"
    },
    {
     "name": "STOCKS group video/effects/bloom/bypassed",
     "path": "/composition/groups/1/video/effects/bloom/bypassed"
    },
    {
     "name": "STOCKS group video/effects/infinitezoom/bypassed",
     "path": "/composition/groups/1/video/effects/infinitezoom/bypassed"
    },
    {
     "name": "STOCKS group video/effects/edgedetection/bypassed",
     "path": "/composition/groups/1/video/effects/edgedetection/bypassed"
    },
    {
     "name": "STOCKS group video/effects/huerotate/bypassed",
     "path": "/composition/groups/1/video/effects/huerotate/bypassed"
    },
    {
     "name": "STOCKS group video/effects/shiftglitch/bypassed",
     "path": "/composition/groups/1/video/effects/shiftglitch/bypassed"
    }
   ],
   "hex": null,
   "kind": "note",
   "num": 103,
   "ch": 1,
   "name": "BANK"
  }
 ],
 "bridge": [
  {
   "kind": "note",
   "num": 7,
   "ch": 16,
   "label": "tempo resync",
   "path": "/composition/tempocontroller/resync"
  },
  {
   "kind": "cc",
   "num": 24,
   "ch": 16,
   "label": "STOCKS group dashboard/link1",
   "path": "/composition/groups/1/dashboard/link1"
  },
  {
   "kind": "cc",
   "num": 15,
   "ch": 16,
   "label": "launch FX 1 clip 2 (GeneraXYZ_07)",
   "path": "/composition/layers/12/clips/2/connect"
  },
  {
   "kind": "note",
   "num": 13,
   "ch": 1,
   "label": "STOCKS group dashboard/link1",
   "path": "/composition/groups/1/dashboard/link1"
  },
  {
   "kind": "note",
   "num": 11,
   "ch": 16,
   "label": "boomer exposure (composition FX)",
   "path": "/composition/video/effects/boomer/effect/exposure"
  },
  {
   "kind": "note",
   "num": 4,
   "ch": 16,
   "label": "master",
   "path": "/composition/master"
  },
  {
   "kind": "cc",
   "num": 15,
   "ch": 16,
   "label": "FX 1 clip 2 (GeneraXYZ_07) video/opacity",
   "path": "/composition/layers/12/clips/2/video/opacity"
  },
  {
   "kind": "note",
   "num": 0,
   "ch": 16,
   "label": "launch FX 1 clip 3 (FLASH MASTER)",
   "path": "/composition/layers/12/clips/3/connect"
  },
  {
   "kind": "cc",
   "num": 20,
   "ch": 16,
   "label": "launch FX 1 clip 8 (SUCK IT!)",
   "path": "/composition/layers/12/clips/8/connect"
  },
  {
   "kind": "note",
   "num": 3,
   "ch": 16,
   "label": "STOCKS group bypassed",
   "path": "/composition/groups/1/bypassed"
  },
  {
   "kind": "note",
   "num": 6,
   "ch": 16,
   "label": "pusher2 push! (composition FX)",
   "path": "/composition/video/effects/pusher2/effect/push!"
  },
  {
   "kind": "cc",
   "num": 18,
   "ch": 16,
   "label": "master",
   "path": "/composition/master"
  },
  {
   "kind": "note",
   "num": 2,
   "ch": 16,
   "label": "launch FX 1 clip 4 (FLASH MASTER)",
   "path": "/composition/layers/12/clips/4/connect"
  },
  {
   "kind": "note",
   "num": 8,
   "ch": 16,
   "label": "tempo tap",
   "path": "/composition/tempocontroller/tempotap"
  },
  {
   "kind": "note",
   "num": 12,
   "ch": 16,
   "label": "master",
   "path": "/composition/master"
  },
  {
   "kind": "note",
   "num": 5,
   "ch": 16,
   "label": "pusher push! (composition FX)",
   "path": "/composition/video/effects/pusher/effect/push!"
  },
  {
   "kind": "note",
   "num": 10,
   "ch": 16,
   "label": "boomer blow (composition FX)",
   "path": "/composition/video/effects/boomer/effect/blow"
  },
  {
   "kind": "cc",
   "num": 16,
   "ch": 16,
   "label": "master",
   "path": "/composition/master"
  },
  {
   "kind": "cc",
   "num": 22,
   "ch": 16,
   "label": "STOCKS group dashboard/link1",
   "path": "/composition/groups/1/dashboard/link1"
  },
  {
   "kind": "note",
   "num": 1,
   "ch": 16,
   "label": "LOGOS group bypassed",
   "path": "/composition/groups/3/bypassed"
  }
 ]
};
